apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-2"
  labels:
    app: "nginx-2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-2"
  template:
    metadata:
      labels:
        app: "nginx-2"
    spec:
      containers:
      - name: "java-application-new-1"
        #image: "asia-south2-docker.pkg.dev/vishwas-426408/jenkins-repo/java-application-new:76"
        ports:
            - containerPort: 8080
      - name: "nginx-3"
        image: "nginx:latest"
        
--- # Services

apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-1
  ports:
    - port: 8080
      targetPort: 8080
